### ISSUE TITLE
"configure" missing in 1.3.0 release

### ISSUE THREAD

**Issue by aabdnn** [DNS-OARC/PacketQ#47]
The 1.3.0 tarball is missing "configure". I assume a user now requires autoconf to create a "configure" script, but this is not usual. Are you able to provide a tarball that has the configure script in it please?

**Comment by jelu** [comment]
Nope, it's there in https://www.dns-oarc.net/tools/packetq :
```
$ tar ztvf packetq-1.3.0.tar.gz |grep configure
-rw-rw-r-- 1000/1000      2026 2017-05-23 11:36 packetq-1.3.0/configure.ac
-rwxr-xr-x 1000/1000    194472 2017-05-23 11:48 packetq-1.3.0/configure
```

You probably used GitHub tarballing and that is like cloning so you would need autotools.
