### ISSUE TITLE
arm64: success report

### ISSUE THREAD

**Issue by vielmetti** [DNS-OARC/PacketQ#65]
No additional work was required to make this code work on arm64 (Packet "Type 2A2" server) - it compiled and ran without incident under Ubuntu 16.04 without any porting or code changes necessary when the provided instructions were followed.

All tests passed and the web server worked as expected.

(OK to close this issue, just wanted to report it in case anyone else was ready to try)

**Comment by jelu** [comment]
@vielmetti Thanks for this! I have enabled arm64 arch/processor on LaunchPad for both repositories so that there will be packages for the next release.

**Comment by vielmetti** [comment]
Thanks @jelu . Are there any related projects or repositories to this one that I should give a quick try for arm64?

**Comment by jelu** [comment]
@vielmetti if your into DNS research then [dnscap](https://github.com/DNS-OARC/dnscap) may be something
