### ISSUE TITLE
Why does packetQ Output nothing？

### ISSUE THREAD

**Issue by IDJack** [DNS-OARC/PacketQ#66]
I use _tcpdump_ to capture all traffic of the local DNS server in my university and save as pcap format.
Then I use _tshark_ to exact some DNS traffic.  
However, I use packetQ to analyze the traffic exacted by tshark and it output nothing? What's wrong?
If I use packetQ to analyze the traffic which is capture by tcpdump and not filter, it can work.

I use packetq1.4.1 and Ubuntu16.

The file 1w.pcap [1w.pcap.zip](https://github.com/DNS-OARC/PacketQ/files/1557752/1w.pcap.zip) is the sample traffic exacted by tshark. You can test on it.

**Comment by jelu** [comment]
PacketQ can not match your traffic because the queries comes in on VLAN 30 but the answer is not VLAN tagged, you could try [scrubbing the VLAN from your PCAPs](https://osqa-ask.wireshark.org/questions/21001/how-to-remove-vlan-tag-from-trace).
