### ISSUE TITLE
Failure to specify a source file gives non-JSON output

### ISSUE THREAD

**Issue by OleLaursen** [DNS-OARC/PacketQ#8]
$ packetq -s "select count(*) from dns;" does-not-exist.pcap.gz
[
Error: No source rows found
]

Stupid error, but I do expect to get some kind of JSON back? (Or then at least not the brackets. :)

**Comment by jelu** [comment]
This does not seem to be a problem anymore:
```shell
$ src/packetq -s "select count(*) from dns" does-not-exist.pcap
```
```json
[
  {
    "table_name": "result-0",
    "query": "select count(*) from dns",
    "head": [
      { "name": "count(1)","type": "int" }
    ],
    "data": [
    ]
  }
]
```
