### ISSUE TITLE
non-ascii names are not escaped properly or replaced by $

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/PacketQ#91]
Version: 948c28e (1.4.3 + commits on top)

Some non-alphanumeric ASCII characters are incorrectly escaped, and other values are outright replaced with `$` character.

Example pcap demostrating the problem: [pcap.pcap.gz](https://github.com/DNS-OARC/PacketQ/files/7179374/pcap.pcap.gz)

The PCAP contains queries generated by equivalent of ```$ dig test "'" '"' '$' dig '\\' dig '\000' '\255'```

packetq command: `$ packetq --csv -s 'select qname from dns where qr=1' /tmp/gh/pcap.pcap.gz`

Got
----
```
"qname"
"test."
"'."
"\"."
"$."
"\\."
"$."
"$."
```

Expected
-------------
```
"qname"
"qname"
"test."
"\'."
"\"."
"\$."
"\\."
"\000."
"\255."
```

**Comment by jelu** [comment]
You're expecting RFC1035 strings when it's more or less a SQL/database.

The output is not RFC1035.

Only issue I see here is the `$`.

**Comment by jelu** [comment]
Btw, have you looked at the actual output? I think `$` might be your terminal showing non-printable characters that way.

**Comment by pspacek** [comment]
It's most certainly not my terminal:
```
$ packetq --csv -s 'select qname from dns where qr=1' /tmp/gh/pcap.pcap.gz | hexdump -c
0000000   "   q   n   a   m   e   "  \n   "   t   e   s   t   .   "  \n
0000010   "   '   .   "  \n   "   \   "   .   "  \n   "   $   .   "  \n
0000020   "   \   \   .   "  \n   "   $   .   "  \n   "   $   .   "  \n
$ packetq --csv -s 'select qname from dns where qr=1' /tmp/gh/pcap.pcap.gz | hexdump -e '"%07.7_ax  " 16/1 "% 3x " "\n"'
0000000   22  71  6e  61  6d  65  22   a  22  74  65  73  74  2e  22   a
0000010   22  27  2e  22   a  22  5c  22  2e  22   a  22  24  2e  22   a
0000020   22  5c  5c  2e  22   a  22  24  2e  22   a  22  24  2e  22   a
```

**Comment by jelu** [comment]
PacketQ [converts non-printable characters](https://github.com/DNS-OARC/PacketQ/blob/948c28e0771d657367e2053c72ae9e0af00afdc5/src/dns.cpp#L39) in it's internal database to `$`.

So the output your getting is expected.

I have no idea why this is but changing it may have severe impact on the engine, indexes, sorting etc.

If you wish to change this then please do the work and send in patches, it will be a major release since it will break backwards compatibility so expect very long time until release.

**Comment by pspacek** [comment]
Okay, I understand it is an unfortunate design of the past. Please leave it open so other people who struggle with this can find it easily.
